# Generated by Django 6.0.3 on 2026-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="value",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
