# Generated by Django 6.0.3 on 2026-03-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_embedding_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="dist",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="embedding",
            name="perturbation_gene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="db.gene",
            ),
        ),
    ]
